<div class="magecomp-extenion-content">
   <?php if( $this->getExtensions()!=""){?>
    <table>
        <tr>
            <th rowspan="2"></th>
            <th colspan="2" style="text-align: center;"><?php echo __("Versions");?></th>
            <th rowspan="2"></th>
        </tr>
        <tr>
            <th><?php echo __("Current");?></th>
            <th><?php echo __("Available");?></th>
        </tr>
        <?php echo $this->getExtensions();?>
    </table>
    <?php }else{?>
            <span style="color:red"><?php echo __("No Extension Found !")?></span>
    <?php }?>
</div>
