<?php
$_item = $block->getItem();
$viewModel = $block->getViewModel();
$block->setPriceDataObject($_item);

?>
<tr>
    <?php
    $i = 0;
    $columns = $block->getColumns();
    $lastItemNumber = count($columns);

    $product = $_item->getProduct();
    $image_url = $viewModel->getImageUrl($product);

    if ($viewModel->isEnbaled()) { ?>
        <td>
            <img src="<?php echo $image_url; ?>"/>
        </td>
    <?php } ?>

    <?php foreach ($columns as $columnName => $columnClass): ?>
        <?php $i++; ?>
        <td class="<?= /* @noEscape */ $columnClass ?><?= /* @noEscape */ ($i === $lastItemNumber ? ' last' : '') ?>">
            <?= /* @escapeNotVerified */ $block->getColumnHtml($_item, $columnName) ?>
        </td>
    <?php endforeach; ?>
</tr>




